apiVersion: apps/v1
kind: Deployment
metadata:
  name: botrunrun-deploy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botrunrun
  template:
    metadata:
      labels:
        app: botrunrun
    spec:
      containers:
        - name: botrunrun
          image: asia-east1-docker.pkg.dev/ak-central-matrix/akousist-registry/botrunrun-job:0.0.2
          imagePullPolicy: Always

