apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev  # Specify the correct namespace
  name: job-creator
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]
