apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-binding
  namespace: dev  # Specify the correct namespace
subjects:
  - kind: ServiceAccount
    name: default  # This binds to the default service account
    namespace: dev  # Ensure this matches the pod's namespace
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io
